name = "sieve"
main = "worker.js"
compatibility_date = "2026-09-01"
workers_dev = true
routes = [{ pattern = "sieve.heyitsmejosh.com", custom_domain = true }]

[assets]
directory = "landing"
binding = "ASSETS"

[[kv_namespaces]]
binding = "RUNS"
id = "aa7d8daf7c694d74862411b46457d7dc"

[observability]
enabled = true
